import time
from MyLife import MyLife

my_life = MyLife.create_first_process()
time.sleep(1)
my_life.act('Hello World')
time.sleep(2)
first_person = my_life.act('NEW_PERSON', official=True)
time.sleep(1)
first_person.act("CHANGE_NAME Adrian", official=True)
time.sleep(1)
first_person.act('We agreed to have a permanent line of credit in Cambodian riels. 1 = 1000 riels')
time.sleep(1)
debt11 = first_person.act('NEW_DEAL', official=True)
time.sleep(1)
debt11.act('CHANGE_CURRENCY k_riel', official=True)
time.sleep(1)
debt11.act('TAKE 11', official=True)
time.sleep(1)
debt11.act('GIVE 6', official=True)
debt11.act('Gym')
time.sleep(4)
debt11.act('GIVE 8', official=True)
debt11.act('Gym')
time.sleep(1)
debt11.act('TAKE 6', official=True)
debt11.act('Phone balance')
time.sleep(1)
debt11.act('GIVE 100', official=True)
debt11.act('payment from  my student')
time.sleep(7)
debt11.act('GIVE 6', official=True)
debt11.act('Gym')
time.sleep(4)
debt11.act('GIVE 100', official=True)
debt11.act('payment from  my student')
time.sleep(1)
second_person = my_life.act('NEW_PERSON', official=True)
time.sleep(1)
second_person.act("CHANGE_NAME Richard", official=True)
time.sleep(1)
my_life.act('Some another information about myself')
time.sleep(1)
debt11.act('GIVE 8', official=True)
debt11.act('Gym')
time.sleep(4)
debt11.act('TAKE 6', official=True)
debt11.act('Phone balance')
time.sleep(1)
debt12 = first_person.act('NEW_DEAL', official=True)
time.sleep(1)
debt12.act('I rent a room for $120 a month')
time.sleep(1)
debt21 = second_person.act('NEW_DEAL', official=True)
time.sleep(1)
debt21.act('TAKE 300', official=True)
time.sleep(1)
debt21.act('I should give it back before my birthday')
time.sleep(1)
debt21.act('SET_REMINDER 23.06.2025-12:00:00 It is 24 hours to give back', official=True)
time.sleep(1)
debt13 = first_person.act('NEW_DEAL', official=True)
time.sleep(3)
debt13.act('GIVE 160', official=True)
debt13.act('I sold you my air conditioner for $160.')
debt13.act('You can pay back for it while I am paying the rent for my room.')
time.sleep(3)
debt12.act('TAKE 120', official=True)
debt12.act('Rent')
debt12.act(f'CROSS {debt13.get_identifier()[0]}', official=True)
debt13.act('TAKE 120', official=True)
debt13.act('Rent')
debt12.act('GIVE 120', official=True)
time.sleep(7)
debt11.act('TAKE 11', official=True)
time.sleep(1)
debt11.act('GIVE 6', official=True)
debt11.act('Gym')
time.sleep(4)
debt11.act('GIVE 8', official=True)
debt11.act('Gym')
time.sleep(1)
debt11.act('TAKE 6', official=True)
debt11.act('Phone balance')
time.sleep(1)
debt11.act('GIVE 100', official=True)
debt11.act('payment from  my student')
time.sleep(7)
debt11.act('GIVE 6', official=True)
debt11.act('Gym')
time.sleep(4)
debt11.act('GIVE 100', official=True)
debt11.act('payment from  my student')
time.sleep(1)
debt12.act('TAKE 120', official=True)
debt12.act('Rent')
debt12.act(f'CROSS {debt13.get_identifier()[0]}', official=True)
debt13.act('TAKE 40', official=True)
debt13.act('Part of the rent')
debt12.act('GIVE 40', official=True)
time.sleep(1)
debt12.act('$80 = 320 k_riel')
debt12.act(f'CROSS {debt11.get_identifier()[0]}', official=True)
debt11.act('TAKE 320', official=True)
debt11.act('Part of the rent')
debt12.act('GIVE 80', official=True)


print(my_life)
print(first_person)
print(second_person)
