import time
from MyLife import MyLife

my_life = MyLife.create_first_process()
time.sleep(1)
my_life.act('Первое сообщение в первом процессе')
time.sleep(1)
first_person = my_life.act('NEW_PERSON', official=True)
time.sleep(1)
first_person.act('Первое сообщение во втором процессе')
time.sleep(1)
second_person = my_life.act('NEW_PERSON', official=True)
time.sleep(1)
second_person.act('Первое сообщение в третьем процессе')
time.sleep(1)
first_person.act("CHANGE_NAME Jonny", official=True)
time.sleep(1)
second_person.act("CHANGE_NAME Richard", official=True)
time.sleep(1)
second_person.act(f'CROSS {first_person.get_identifier()[0]}', official=True)
time.sleep(1)
my_life.act('Второе сообщение в первом процессе')
time.sleep(1)
first_person.act('Второе сообщение во втором процессе')
time.sleep(1)
second_person.act('Второе сообщение в третьем процессе')
time.sleep(1)

debt11 = first_person.act('NEW_DEBT', official=True)
time.sleep(1)
debt11.act('Первое сообщение в четвёртом процессе')
time.sleep(1)

debt21 = second_person.act('NEW_DEBT', official=True)
time.sleep(1)
debt21.act('Первое сообщение в пятом процессе')
time.sleep(1)

debt11.act('Второе сообщение в четвёртом процессе')
time.sleep(1)
debt11.act('TAKE 100', official=True)
time.sleep(1)
debt21.act('Второе сообщение в пятом процессе')
time.sleep(1)
debt11.act('GIVE 100', official=True)
time.sleep(1)
debt21.act('GIVE 50', official=True)
time.sleep(1)
debt21.act('TAKE 50', official=True)
time.sleep(1)

debt21.act('CHANGE_CURRENCY ru', official=True)
time.sleep(1)

debt12 = first_person.act('NEW_DEBT', official=True)
time.sleep(1)
first_person.act('Третье сообщение во втором процессе')
time.sleep(1)
debt12.act('TAKE 50', official=True)
time.sleep(1)
debt12.act('Первое сообщение в 6 процессе')
time.sleep(1)

debt22 = second_person.act('NEW_DEBT', official=True)
time.sleep(1)
debt12.act('GIVE 30', official=True)
debt12.act('SET_REMINDER 24.06.2025-15:00:00 Мне будет 38 лет', official=True)
time.sleep(1)
debt22.act('Первое сообщение в 7 процессе')
time.sleep(1)
my_life.act('SET_REMINDER 24.06.2025-15:15:15 Мне будет 38 лет', official=True)
time.sleep(1)
first_person.act('SET_REMINDER 15.04.2025-15:15:15 Тестовое нопоминание', official=True)
time.sleep(1)
second_person.act('SET_REMINDER 16.04.2025-15:15:15 Тестовое нопоминание', official=True)
time.sleep(1)
debt22.act('SET_REMINDER 17.04.2025-15:15:15 Тестовое нопоминание', official=True)
time.sleep(1)
debt21.act('SET_REMINDER 18.04.2025-15:15:15 Тестовое нопоминание', official=True)

print(my_life)
print(first_person)
print(second_person)
